[Astro]
file = /data/CARD_singlecell/SN_atlas/data/pycisTopic/consensus_peak_calling/pseudobulk_bw_files/Astro.bw
# height of the track in cm (optional value)
height = 2
min_value = 0
max_value = 3
color = Blue
title = Astro

[DaN]
file = /data/CARD_singlecell/SN_atlas/data/pycisTopic/consensus_peak_calling/pseudobulk_bw_files/DaN.bw
# height of the track in cm (optional value)
height = 2
min_value = 0
max_value = 3
color = Orange
title = DaN

[EC]
file = /data/CARD_singlecell/SN_atlas/data/pycisTopic/consensus_peak_calling/pseudobulk_bw_files/EC.bw
# height of the track in cm (optional value)
height = 2
min_value = 0
max_value = 3
color = Green
title = EC

[ExN]
file = /data/CARD_singlecell/SN_atlas/data/pycisTopic/consensus_peak_calling/pseudobulk_bw_files/ExN.bw
# height of the track in cm (optional value)
height = 2
min_value = 0
max_value = 3
color = Red
title = ExN

[InN]
file = /data/CARD_singlecell/SN_atlas/data/pycisTopic/consensus_peak_calling/pseudobulk_bw_files/InN.bw
# height of the track in cm (optional value)
height = 2
min_value = 0
max_value = 3
color = Purple
title = InN

[MG]
file = /data/CARD_singlecell/SN_atlas/data/pycisTopic/consensus_peak_calling/pseudobulk_bw_files/MG.bw
# height of the track in cm (optional value)
height = 2
min_value = 0
max_value = 3
color = Brown
title = MG

[OPC]
file = /data/CARD_singlecell/SN_atlas/data/pycisTopic/consensus_peak_calling/pseudobulk_bw_files/OPC.bw
# height of the track in cm (optional value)
height = 2
min_value = 0
max_value = 3
color = Pink
title = OPC

[Oligo]
file = /data/CARD_singlecell/SN_atlas/data/pycisTopic/consensus_peak_calling/pseudobulk_bw_files/Oligo.bw
# height of the track in cm (optional value)
height = 2
min_value = 0
max_value = 3
color = Grey
title = Oligo

[PC]
file = /data/CARD_singlecell/SN_atlas/data/pycisTopic/consensus_peak_calling/pseudobulk_bw_files/PC.bw
# height of the track in cm (optional value)
height = 2
min_value = 0
max_value = 3
color = limegreen
title = PC

[TC]
file = /data/CARD_singlecell/SN_atlas/data/pycisTopic/consensus_peak_calling/pseudobulk_bw_files/TC.bw
# height of the track in cm (optional value)
height = 2
min_value = 0
max_value = 3
color = aqua
title = TC

